// Code generated by "enumer -type=Status -json -trimprefix=Status -transform=lower"; DO NOT EDIT.

package hash

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _StatusName = "okmismatcherrorrunning"

var _StatusIndex = [...]uint8{0, 2, 10, 15, 22}

const _StatusLowerName = "okmismatcherrorrunning"

func (i Status) String() string {
	i -= 1
	if i < 0 || i >= Status(len(_StatusIndex)-1) {
		return fmt.Sprintf("Status(%d)", i+1)
	}
	return _StatusName[_StatusIndex[i]:_StatusIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _StatusNoOp() {
	var x [1]struct{}
	_ = x[StatusOK-(1)]
	_ = x[StatusMismatch-(2)]
	_ = x[StatusError-(3)]
	_ = x[StatusRunning-(4)]
}

var _StatusValues = []Status{StatusOK, StatusMismatch, StatusError, StatusRunning}

var _StatusNameToValueMap = map[string]Status{
	_StatusName[0:2]:        StatusOK,
	_StatusLowerName[0:2]:   StatusOK,
	_StatusName[2:10]:       StatusMismatch,
	_StatusLowerName[2:10]:  StatusMismatch,
	_StatusName[10:15]:      StatusError,
	_StatusLowerName[10:15]: StatusError,
	_StatusName[15:22]:      StatusRunning,
	_StatusLowerName[15:22]: StatusRunning,
}

var _StatusNames = []string{
	_StatusName[0:2],
	_StatusName[2:10],
	_StatusName[10:15],
	_StatusName[15:22],
}

// StatusString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func StatusString(s string) (Status, error) {
	if val, ok := _StatusNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _StatusNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to Status values", s)
}

// StatusValues returns all values of the enum
func StatusValues() []Status {
	return _StatusValues
}

// StatusStrings returns a slice of all String values of the enum
func StatusStrings() []string {
	strs := make([]string, len(_StatusNames))
	copy(strs, _StatusNames)
	return strs
}

// IsAStatus returns "true" if the value is listed in the enum definition. "false" otherwise
func (i Status) IsAStatus() bool {
	for _, v := range _StatusValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for Status
func (i Status) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for Status
func (i *Status) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("Status should be a string, got %s", data)
	}

	var err error
	*i, err = StatusString(s)
	return err
}
