// Code generated by "enumer -type=Kind -json -linecomment"; DO NOT EDIT.

package tileset

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _KindName = "mbtilespmtiles"

var _KindIndex = [...]uint8{0, 7, 14}

const _KindLowerName = "mbtilespmtiles"

func (i Kind) String() string {
	if i < 0 || i >= Kind(len(_KindIndex)-1) {
		return fmt.Sprintf("Kind(%d)", i)
	}
	return _KindName[_KindIndex[i]:_KindIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _KindNoOp() {
	var x [1]struct{}
	_ = x[KindMBTiles-(0)]
	_ = x[KindPMTiles-(1)]
}

var _KindValues = []Kind{KindMBTiles, KindPMTiles}

var _KindNameToValueMap = map[string]Kind{
	_KindName[0:7]:       KindMBTiles,
	_KindLowerName[0:7]:  KindMBTiles,
	_KindName[7:14]:      KindPMTiles,
	_KindLowerName[7:14]: KindPMTiles,
}

var _KindNames = []string{
	_KindName[0:7],
	_KindName[7:14],
}

// KindString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func KindString(s string) (Kind, error) {
	if val, ok := _KindNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _KindNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to Kind values", s)
}

// KindValues returns all values of the enum
func KindValues() []Kind {
	return _KindValues
}

// KindStrings returns a slice of all String values of the enum
func KindStrings() []string {
	strs := make([]string, len(_KindNames))
	copy(strs, _KindNames)
	return strs
}

// IsAKind returns "true" if the value is listed in the enum definition. "false" otherwise
func (i Kind) IsAKind() bool {
	for _, v := range _KindValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for Kind
func (i Kind) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for Kind
func (i *Kind) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("Kind should be a string, got %s", data)
	}

	var err error
	*i, err = KindString(s)
	return err
}
