// Code generated by "enumer -type=Status -json -trimprefix=Status -transform=lower"; DO NOT EDIT.

package download

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _StatusName = "runningpausederrordonecancelled"

var _StatusIndex = [...]uint8{0, 7, 13, 18, 22, 31}

const _StatusLowerName = "runningpausederrordonecancelled"

func (i Status) String() string {
	if i < 0 || i >= Status(len(_StatusIndex)-1) {
		return fmt.Sprintf("Status(%d)", i)
	}
	return _StatusName[_StatusIndex[i]:_StatusIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _StatusNoOp() {
	var x [1]struct{}
	_ = x[StatusRunning-(0)]
	_ = x[StatusPaused-(1)]
	_ = x[StatusError-(2)]
	_ = x[StatusDone-(3)]
	_ = x[StatusCancelled-(4)]
}

var _StatusValues = []Status{StatusRunning, StatusPaused, StatusError, StatusDone, StatusCancelled}

var _StatusNameToValueMap = map[string]Status{
	_StatusName[0:7]:        StatusRunning,
	_StatusLowerName[0:7]:   StatusRunning,
	_StatusName[7:13]:       StatusPaused,
	_StatusLowerName[7:13]:  StatusPaused,
	_StatusName[13:18]:      StatusError,
	_StatusLowerName[13:18]: StatusError,
	_StatusName[18:22]:      StatusDone,
	_StatusLowerName[18:22]: StatusDone,
	_StatusName[22:31]:      StatusCancelled,
	_StatusLowerName[22:31]: StatusCancelled,
}

var _StatusNames = []string{
	_StatusName[0:7],
	_StatusName[7:13],
	_StatusName[13:18],
	_StatusName[18:22],
	_StatusName[22:31],
}

// StatusString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func StatusString(s string) (Status, error) {
	if val, ok := _StatusNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _StatusNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to Status values", s)
}

// StatusValues returns all values of the enum
func StatusValues() []Status {
	return _StatusValues
}

// StatusStrings returns a slice of all String values of the enum
func StatusStrings() []string {
	strs := make([]string, len(_StatusNames))
	copy(strs, _StatusNames)
	return strs
}

// IsAStatus returns "true" if the value is listed in the enum definition. "false" otherwise
func (i Status) IsAStatus() bool {
	for _, v := range _StatusValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for Status
func (i Status) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for Status
func (i *Status) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("Status should be a string, got %s", data)
	}

	var err error
	*i, err = StatusString(s)
	return err
}
